### ISSUE TITLE
[3주차] 그리디

### ISSUE THREAD

**Issue by gomdoricake** [TeamCrazyPerformance/algorithm2022-2-Fri#4]
### 다음 주 공부 주제

이분 탐색

### 문제 (그리디)

- [x] [4796](https://www.acmicpc.net/problem/4796)
- [x] [2864](https://www.acmicpc.net/problem/2864)
- [ ] [1931](https://www.acmicpc.net/problem/1931)
- [ ] [1080](https://www.acmicpc.net/problem/1080)
- [x] [1783](https://www.acmicpc.net/problem/1783)
- [ ] ~~[10775](https://www.acmicpc.net/problem/10775)~~ [1339](https://www.acmicpc.net/problem/1339)

추가문제 (완전 탐색)
- [ ] [1107](https://www.acmicpc.net/problem/1107)

**Comment by wlsh44** [comment]
- [x] [4796](https://www.acmicpc.net/problem/4796)
- [x] [2864](https://www.acmicpc.net/problem/2864)
- [x] [1931](https://www.acmicpc.net/problem/1931)
- [x] [1080](https://www.acmicpc.net/problem/1080)
- [x] [1783](https://www.acmicpc.net/problem/1783)
- [x] [10775](https://www.acmicpc.net/problem/10775)
- [x] [1339](https://www.acmicpc.net/problem/1339)
- [x] [1107](https://www.acmicpc.net/problem/1107)
